sudo: false
language: python
python:
    - "2.7"
#    - "3.3"  # End-of-life September 2017
    - "3.4"
    - "3.5"
    - "3.6"
    # See yaml/pyyaml#126.
#    - "3.7-dev"  # Planned for 2018-06

#sudo: required
before_install:
    # See issue #80: litmus fails to build on travis
    # The branch 'travis-litmus' still has this enabled to investigate...
#    - sudo apt-get install libneon27-dev
#    - ./install_litmus.sh
     - docker-compose up -d
     - docker ps
     - sleep 16
     - docker run --network=wsgidav_local --rm -ti mar10/docker-litmus http://wsgidav:8080/ tester secret
install:
    pip install tox-travis
script:
    tox
